server:
  host: "localhost"
  port: 8089
  cors: "http://localhost:5500"

# Database Credentials
database:
  host: "172.17.0.2"
  name: "test"
  user: "postgres"
  password: "mysecretpassword"
  port: 5432

auth:
  jwtkey: "mysecretkey12345mysecretkey12345"
  jwtkeysize: 32

pagination:
  perpage : 5
  defaultpage: 1